<?php
if (session_status() === PHP_SESSION_NONE) { session_start(); }

function setLangFromRequest(): void {
    if (isset($_GET['lang']) && in_array($_GET['lang'], ['tr','en'], true)) {
        $_SESSION['lang'] = $_GET['lang'];
    }
}

function getLang(): string {
    return $_SESSION['lang'] ?? 'tr';
}

function t(string $key): string {
    static $dict = [
        'tr' => [
            'emergency_profile' => 'Acil Profil',
            'viewed_via_qr' => 'Bu sayfa NFC/QR ile görüntülendi',
            'print_pdf' => 'PDF Yazdır',
            'open_link' => 'Bağlantı',
            'emergency_contact' => 'Acil İletişim',
            'person' => 'Kişi',
            'phone' => 'Telefon',
            'call_now' => 'Hemen Ara',
            'address' => 'Adres',
            'open_maps' => 'Haritada Aç',
            'doctor_info' => 'Doktor Bilgisi',
            'doctor' => 'Doktor',
            'medications' => 'İlaçlar',
            'other_info' => 'Diğer Bilgiler',
            'home' => 'Ana Sayfa',
            // Auth
            'sign_in' => 'Giriş Yap',
            'sign_up' => 'Kayıt Ol',
            'login_title' => 'Giriş Yap - ARDİO',
            'register_title' => 'Kayıt Ol - ARDİO',
            'email' => 'E-posta',
            'password' => 'Şifre',
            'password_confirm' => 'Şifre Tekrar',
            'no_account' => 'Hesabın yok mu?',
            'have_account' => 'Hesabın var mı?',
            'error_invalid_credentials' => 'Hatalı şifre veya e-posta.',
            'server_error' => 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
            'fill_all_fields' => 'Lütfen tüm alanları doldurun.',
            'invalid_email' => 'Geçerli bir e-posta girin.',
            'passwords_mismatch' => 'Şifreler uyuşmuyor.',
            'email_exists' => 'Bu e-posta zaten kayıtlı.',
            'register_success' => 'Kayıt başarılı! Giriş yapabilirsiniz.',
            // Navbar/common
            'logout' => 'Çıkış Yap',
            'admin' => 'Admin',
            'panel' => 'Panel',
            'language' => 'Dil',
            'turkish' => 'Türkçe',
            'english' => 'English',
            // Admin
            'admin_panel' => 'Admin Paneli - ARDİO',
            'site_settings' => 'Site Ayarları',
            'analytics' => 'Analitik',
            'return_to_admin' => 'Admin’e Geri Dön',
            'users' => 'Kullanıcılar',
            'total' => 'Toplam',
            'export_csv' => 'CSV Dışa Aktar',
            'new_user' => 'Yeni Kullanıcı',
            'search' => 'Ara',
            'role' => 'Rol',
            'all' => 'Hepsi',
            'data' => 'Veri',
            'has_data' => 'Hasta verisi var',
            'no_data' => 'Hasta verisi yok',
            'page_size' => 'Sayfa boyutu',
            'apply' => 'Uygula',
            'clear' => 'Temizle',
            'bulk_action_select' => 'Toplu işlem seçin…',
            'delete_selected' => 'Seçilenleri Sil',
            'make_admin_selected' => 'Seçilenleri Admin Yap',
            'make_user_selected' => 'Seçilenleri Kullanıcı Yap',
            'select_all' => 'Tümünü Seç',
        ],
        'en' => [
            'emergency_profile' => 'Emergency Profile',
            'viewed_via_qr' => 'This page is opened via NFC/QR',
            'print_pdf' => 'Print PDF',
            'open_link' => 'Open Link',
            'emergency_contact' => 'Emergency Contact',
            'person' => 'Person',
            'phone' => 'Phone',
            'call_now' => 'Call Now',
            'address' => 'Address',
            'open_maps' => 'Open in Maps',
            'doctor_info' => 'Doctor Info',
            'doctor' => 'Doctor',
            'medications' => 'Medications',
            'other_info' => 'Other Info',
            'home' => 'Home',
            // Auth
            'sign_in' => 'Sign In',
            'sign_up' => 'Sign Up',
            'login_title' => 'Sign In - ARDİO',
            'register_title' => 'Sign Up - ARDİO',
            'email' => 'Email',
            'password' => 'Password',
            'password_confirm' => 'Password Confirm',
            'no_account' => "Don't have an account?",
            'have_account' => 'Already have an account?',
            'error_invalid_credentials' => 'Invalid email or password.',
            'server_error' => 'Server error. Please try again later.',
            'fill_all_fields' => 'Please fill in all fields.',
            'invalid_email' => 'Please enter a valid email.',
            'passwords_mismatch' => "Passwords don't match.",
            'email_exists' => 'This email is already registered.',
            'register_success' => 'Registration successful! You can sign in.',
            // Navbar/common
            'logout' => 'Logout',
            'admin' => 'Admin',
            'panel' => 'Panel',
            'language' => 'Language',
            'turkish' => 'Turkish',
            'english' => 'English',
            // Admin
            'admin_panel' => 'Admin Panel - ARDİO',
            'site_settings' => 'Site Settings',
            'analytics' => 'Analytics',
            'return_to_admin' => 'Return to Admin',
            'users' => 'Users',
            'total' => 'Total',
            'export_csv' => 'Export CSV',
            'new_user' => 'New User',
            'search' => 'Search',
            'role' => 'Role',
            'all' => 'All',
            'data' => 'Data',
            'has_data' => 'Has patient data',
            'no_data' => 'No patient data',
            'page_size' => 'Page size',
            'apply' => 'Apply',
            'clear' => 'Clear',
            'bulk_action_select' => 'Select bulk action…',
            'delete_selected' => 'Delete selected',
            'make_admin_selected' => 'Make selected Admin',
            'make_user_selected' => 'Make selected User',
            'select_all' => 'Select All',
        ],
    ];
    $lang = getLang();
    return $dict[$lang][$key] ?? ($dict['tr'][$key] ?? $key);
}